spring.application.name=demo


#setup JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
#show sql logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# optional: keep the familiar entrypoint
springdoc.swagger-ui.path=/swagger.html


