spring.application.name=demo
# config related to H2 database
##spring.datasource.url=jdbc:h2:mem:obbdb
#spring.datasource.url=jdbc:h2:file:./data/obbdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=


# config related to MySQL database
#spring.datasource.url=jdbc:h2:mem:obbdb
spring.datasource.url=jdbc:mysql://localhost:3306/obbdb?useSSL=false
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=n3u3da!
spring.datasource.hikari.maximum-pool-size=10

#setup JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#show sql logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#configure console for h2 database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

